# ASSIGNMENT_25thFEB_2023_PWSKIILLS

## Consider the below code to answer further questions:
### import numpy as np
### list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
### array_list = np.array(object = list_)
## Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.



In [17]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

### Yes, there is a difference in the data type of variables list_ and array_list.

**list_** has the data type of <class 'list'>

**array_list** has the data type of <class 'numpy.ndarray'>. It is basically a numpy n dimensional array datatype with one dimenion.

In [18]:
# printing the data type of list_ 

print('The data type of list_ is :',type(list_))

# printing the data type of array_list

print('The data type of array_list is : ',type(array_list))

The data type of list_ is : <class 'list'>
The data type of array_list is :  <class 'numpy.ndarray'>


## Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.


In [19]:
# Function to get the data type of every element of list_

def data_type_list(list):
    for i in list:
        print(f'The data type of {i} in list_ is \n: {type(i)}')

# Function to get the data type of every element of array_list
              
def data_type_arraylist(array_list):
    for i in array_list:
        print(f'The data type of {i} in list_ is \n: {type(i)}')
              
              
data_type_list(list_)
data_type_arraylist(array_list)

The data type of 1 in list_ is 
: <class 'str'>
The data type of 2 in list_ is 
: <class 'str'>
The data type of 3 in list_ is 
: <class 'str'>
The data type of 4 in list_ is 
: <class 'str'>
The data type of 5 in list_ is 
: <class 'str'>
The data type of 1 in list_ is 
: <class 'numpy.str_'>
The data type of 2 in list_ is 
: <class 'numpy.str_'>
The data type of 3 in list_ is 
: <class 'numpy.str_'>
The data type of 4 in list_ is 
: <class 'numpy.str_'>
The data type of 5 in list_ is 
: <class 'numpy.str_'>


## Q3. Considering the following changes in the variable, array_list:
### array_list = np.array(object = list_, dtype = int)
### Will there be any difference in the data type of the elements present in both the variables, list_ and
### array_list? If so then print the data types of each and every element present in both the variables, list_
### and array_list.

In [20]:
array_list = np.array(object = list_, dtype = int)

### Yes, There will be differnece in the data type of the element in both the variables, list_ and array_list 

In [21]:
# Print the data type of the every element in variable list_
data_type_list(list_)

# Print the data type of the every element in variable array_list after updation using above code 
data_type_arraylist(array_list)

The data type of 1 in list_ is 
: <class 'str'>
The data type of 2 in list_ is 
: <class 'str'>
The data type of 3 in list_ is 
: <class 'str'>
The data type of 4 in list_ is 
: <class 'str'>
The data type of 5 in list_ is 
: <class 'str'>
The data type of 1 in list_ is 
: <class 'numpy.int32'>
The data type of 2 in list_ is 
: <class 'numpy.int32'>
The data type of 3 in list_ is 
: <class 'numpy.int32'>
The data type of 4 in list_ is 
: <class 'numpy.int32'>
The data type of 5 in list_ is 
: <class 'numpy.int32'>


## Consider the below code to answer further questions:
### import numpy as np
### num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
### num_array = np.array(object = num_list)
## Q4. Write a code to find the following characteristics of variable, num_array:
### (i) shape
### (ii) size


In [23]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

display(num_array)

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
# Code to print the shape of the above array 

print(num_array.shape)

(2, 3)


In [27]:
# Code to print the size of the above array 

print(num_array.size)

6


## Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

### [Hint: The size of the array will be 9 and the shape will be (3,3).]


In [33]:
# Code to print the numpy array containing Zeros

import numpy as np

array_zero = np.zeros((3,3)) # Inbuilt function for numpy array creation

print(array_zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [35]:
type(array_zero)

numpy.ndarray

## Q6. Create an identity matrix of shape (5,5) using numpy functions?
### [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [32]:
# Code to print the identity matrix of shape(5,5) using np.matrix() function

import numpy as np

array_identity = np.matrix(np.identity(5)) # Inbuilt function for matrix creation

print(array_identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [34]:
type(array_identity)

numpy.matrix